# Generated by Django 5.0.6 on 2024-07-30 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articleImages/')),
                ('title', models.CharField(max_length=200)),
                ('article_content', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('adminApproved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(default='New', max_length=50)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(max_length=1500)),
                ('providerComment', models.TextField(default='', max_length=1500)),
                ('assigned_to_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('profession', models.CharField(blank=True, default='', max_length=75, null=True)),
                ('aboutMe', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='userImages/')),
                ('isAdmin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OptimumAPI.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OptimumAPI.tag')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='OptimumAPI.ArticleTag', to='OptimumAPI.tag'),
        ),
    ]
